# Generated by Django 5.1.4 on 2024-12-17 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Descripcion', models.CharField(max_length=40)),
                ('FechaCreacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InfoForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=30)),
                ('opciones', models.TextField(blank=True)),
                ('idFormulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forms.formulario')),
            ],
        ),
    ]
