# Generated by Django 5.1.4 on 2024-12-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0002_rename_descripcion_formulario_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='Fecha_Creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
