# Generated by Django 5.1.4 on 2024-12-18 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0002_alter_infoform_idformulario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoform',
            name='idFormulario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infoForm_set', to='Forms.formulario'),
        ),
    ]
