# Generated by Django 5.1.4 on 2024-12-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0006_alter_infoform_opciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoform',
            name='opciones',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
