# Generated by Django 5.1.4 on 2024-12-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0007_alter_infoform_opciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='Nombre',
            field=models.CharField(max_length=50),
        ),
    ]
