# Generated by Django 5.1.4 on 2024-12-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0008_alter_formulario_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoform',
            name='opciones',
            field=models.TextField(blank=True, default=list),
        ),
    ]
