CREATE DATABASE IF NOT EXISTS Formularios;
USE Formularios;

CREATE TABLE Formulario(
Id_Form INTEGER PRIMARY KEY AUTO_INCREMENT,
Nombre VARCHAR (30) NOT NULL, 
Descripcion VARCHAR (40) NOT NULL, 
Fecha_Creacion DATE NOT NULL
);

CREATE TABLE INFO_FORM(
Id_Info INTEGER PRIMARY KEY AUTO_INCREMENT,
Tipo VARCHAR (20) NOT NULL, 
Titulo VARCHAR (30) NOT NULL, 
Opciones VARCHAR (100) NOT NULL, 
Obligatorio BOOLEAN NOT NULL,
id_Form INTEGER not null, 
FOREIGN KEY (id_Form) 
REFERENCES Formulario(Id_Form)
);


